CREATE TABLE BRANCH(
BNO NUMERIC PRIMARY KEY,
BNAME VARCHAR(10));

INSERT INTO BRANCH VALUES(1, "CSE");
INSERT INTO BRANCH VALUES(2, "AIML");

SELECT * FROM BRANCH;

CREATE TABLE STUDENT
(
SN0 NUMERIC PRIMARY KEY,
NAME VARCHAR(50) NOT NULL UNIQUE,
BRANCH NUMERIC,
ADDRESS VARCHAR(50),
FOREIGN KEY STUDENT(BRANCH) REFERENCES BRANCH (BNO));

INSERT INTO STUDENT VALUES(1, "RAM", 1, "BBSR");
INSERT INTO STUDENT VALUES(2, "SHYAM", 1, "BBSR");
INSERT INTO STUDENT VALUES(3, "SOUMYAB", 1, "BBSR");
INSERT INTO STUDENT VALUES(4, "SOUMYAS", 2, "BBSR");


SELECT * FROM STUDENT;
UPDATE STUDENT SET BRANCH=2 WHERE SN0=3;

ALTER TABLE STUDENT ADD COLUMN CGPA DOUBLE;

UPDATE STUDENT SET CGPA=7.1 WHERE SN0=3;

UPDATE STUDENT SET CGPA=8.4 WHERE SN0=1;
UPDATE STUDENT SET CGPA=7.1 WHERE SN0=2;
DELETE FROM STUDENT WHERE SN0 = 3;
DELETE FROM STUDENT WHERE SN0 = 4;

DELETE FROM BRANCH WHERE BNO=2;
SELECT * FROM BRANCH;

SELECT * FROM STUDENT;

SELECT NAME FROM STUDENT ORDER BY CGPA desc;


